layout_spectrum: 0.3791171006413896
typography_spectrum: 0.16177470026629986
color:
  lightness: 0.7217655855667141
  brandColors:
    - '#FFFFFF'
    - '#181818'
    - '#988982'
    - '#59503D'
    - '#6DD9EF'
  saturation: 0.15336442039910667
  brandStrength: 0.8666754042590498
  rhythmicContrast: 0.5044015286614805
content_rating:
  adult: false
name: 50plus
navigation:
  - name: DAS SIND WIR
    id: ae4bc783-d2dc-406b-98fc-7278453965dc
    type: content
  - name: UNTERSTÜTZEN SIE UNS
    id: c3c164c2-07e0-434c-838d-bce2f51e0027
    type: content
  - name: UNSER VORHABEN
    id: 69066335-9091-429c-a942-592aed3c6c66
    type: content
  - name: FAKTEN
    id: 820cfe39-9e1c-45bf-ab55-e54a99fd83d9
    type: content
title: '50plus '
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FLp8Tn-WmpgY%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DLp8Tn-WmpgY&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FLp8Tn-WmpgY%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: TVnostalgie
          url: 'https://www.youtube.com/user/tevenostalgie'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: www.youtube.com
      keywords:
        - rtl television (tv network)
        - hans meiser
      description: >-
        Legendärer Vorspann zur täglichen Talkshow mit Hans Meier bei RTL. Dies
        war soweit ich weiss der zweite Vorspann der Sendung. Die erste Version
        zum Start habe ich irgendwie mit blauer Farbgebung in Erinnerung. Aber
        vielleicht war's auch gerade umgekehrt :-) +++ EDIT: Es war umgekehrt.
        Dies war tatsächlich das erste Intro von Hans Meiser.
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=Lp8Tn-WmpgY&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=Lp8Tn-WmpgY&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=Lp8Tn-WmpgY&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=Lp8Tn-WmpgY&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=Lp8Tn-WmpgY&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=Lp8Tn-WmpgY'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=Lp8Tn-WmpgY
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=Lp8Tn-WmpgY
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=Lp8Tn-WmpgY'
      title: 'Hans Meiser Intro (RTL, 1992)'
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  Wir berichten über alltägliches im Alter und im Pflegebedarf,  zeigen Lösungen
  auf und geben Hilfestellung.
purpose: []
github: true
author:
  name: Michael Geuer
  email: michael.geuer@gmx.de
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2098087d-3153-4013-a40f-90bfea9a2f0c.jpg
